- name: Update cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ntpdate
      - xdg-utils
      - matlab-2018b
      - libcudnn7
      - nvidia-cuda-toolkit