- name: Copy munge key from master node
  copy:
    src: files/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  register: mungekey

- name: Restart munge
  systemd:
    name: munge
    state: restarted
  when: mungekey.changed