- name: Add UNR CoEn Repository GPG Key
  apt_key:
    url: https://apt.cse.unr.edu/ubuntu/dists/bionic/public.gpg
    state: present

- name: Add UNR CoEn Repository
  apt_repository:
    repo: 'deb https://apt.cse.unr.edu/ubuntu/ bionic main'
    state: present

- name: Update cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - slurm-wlm
      - munge
      - libslurm-dev
      - mpich
      - libpmi0
      - libpmix-dev
      - ntp
      - gcc
      - freeipa-client
      - sssd-tools
      - nfs-common
      - autofs
      - htop
      - make
      - libpmi0
      - mpich