- name: Add UNR CoEn Repository GPG Key
  apt_key:
    url: https://apt.cse.unr.edu/public.gpg
    state: present

- name: Add UNR CoEn Repository
  apt_repository:
    repo: 'deb https://apt.cse.unr.edu/ubuntu/ main'
    state: present

- name: Update cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ntpdate
      - slurm-wlm
      - gcc
      - freeipa-client
      - sssd-tools
      - nfs-common
      - autofs
      - htop
      - make
      - libpmi0
      - mpich
      - xdg-utils