- name: Check for existing munge key
  stat: 
    path: /etc/munge/munge.key
  check_mode: no
  ignore_errors: True
  register: mungekeystatus

- name: Create munge key
  shell: echo "creating munge key"
  args:
    creates: /etc/munge/munge.key

- name: Get munge key from master node
  fetch:
    src: /etc/munge/munge.key
    dest: files/munge.key
    fail_on_missing: yes
    flat: yes